ALTER TABLE `Folders`
    ADD COLUMN `mergeState` VARCHAR(20) NOT NULL DEFAULT 'NONE' COMMENT '合并状态: NONE, PENDING, APPROVED, REJECTED' AFTER `isDelete`,
    ADD COLUMN `targetOrganizationId` VARCHAR(36) DEFAULT NULL COMMENT '请求合并的目标组织ID' AFTER `mergeState`;